[package]
name = "nebula-terminal"
version = "1.0.0"
description = "Nebula Terminal, a terminal for Windows"
authors = ["Awizz"]
edition = "2021"
rust-version = "1.98"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
portable-pty = "0.9.0"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2.11.5", features = [] }
tauri-plugin-opener = "2.5.5"
window-vibrancy = "0.8.0"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
strip = true
