//! GNU coreutils provided by the uutils project, dispatched by name.

use std::ffi::OsString;

/// Every coreutils command Nebula ships, in alphabetical order.
pub const NAMES: &[&str] = &[
    "base64",
    "basename",
    "cat",
    "cksum",
    "comm",
    "cp",
    "cut",
    "date",
    "dd",
    "df",
    "dirname",
    "du",
    "echo",
    "env",
    "expand",
    "expr",
    "false",
    "fmt",
    "fold",
    "head",
    "hostname",
    "join",
    "ln",
    "ls",
    "md5sum",
    "mkdir",
    "mktemp",
    "more",
    "mv",
    "nl",
    "nproc",
    "numfmt",
    "od",
    "paste",
    "printenv",
    "printf",
    "pwd",
    "readlink",
    "realpath",
    "rm",
    "rmdir",
    "seq",
    "sha1sum",
    "sha256sum",
    "sha512sum",
    "shuf",
    "sleep",
    "sort",
    "split",
    "tac",
    "tail",
    "tee",
    "test",
    "touch",
    "tr",
    "true",
    "truncate",
    "uname",
    "unexpand",
    "uniq",
    "unlink",
    "wc",
    "whoami",
    "yes",
    "[",
];

type Main = fn(std::vec::IntoIter<OsString>) -> i32;

fn entry(name: &str) -> Option<Main> {
    Some(match name {
        "base64" => uu_base64::uumain,
        "basename" => uu_basename::uumain,
        "cat" => uu_cat::uumain,
        "cksum" => uu_cksum::uumain,
        "comm" => uu_comm::uumain,
        "cp" => uu_cp::uumain,
        "cut" => uu_cut::uumain,
        "date" => uu_date::uumain,
        "dd" => uu_dd::uumain,
        "df" => uu_df::uumain,
        "dirname" => uu_dirname::uumain,
        "du" => uu_du::uumain,
        "echo" => uu_echo::uumain,
        "env" => uu_env::uumain,
        "expand" => uu_expand::uumain,
        "expr" => uu_expr::uumain,
        "false" => uu_false::uumain,
        "fmt" => uu_fmt::uumain,
        "fold" => uu_fold::uumain,
        "head" => uu_head::uumain,
        "hostname" => uu_hostname::uumain,
        "join" => uu_join::uumain,
        "ln" => uu_ln::uumain,
        "ls" => uu_ls::uumain,
        "md5sum" => uu_md5sum::uumain,
        "mkdir" => uu_mkdir::uumain,
        "mktemp" => uu_mktemp::uumain,
        "more" => uu_more::uumain,
        "mv" => uu_mv::uumain,
        "nl" => uu_nl::uumain,
        "nproc" => uu_nproc::uumain,
        "numfmt" => uu_numfmt::uumain,
        "od" => uu_od::uumain,
        "paste" => uu_paste::uumain,
        "printenv" => uu_printenv::uumain,
        "printf" => uu_printf::uumain,
        "pwd" => uu_pwd::uumain,
        "readlink" => uu_readlink::uumain,
        "realpath" => uu_realpath::uumain,
        "rm" => uu_rm::uumain,
        "rmdir" => uu_rmdir::uumain,
        "seq" => uu_seq::uumain,
        "sha1sum" => uu_sha1sum::uumain,
        "sha256sum" => uu_sha256sum::uumain,
        "sha512sum" => uu_sha512sum::uumain,
        "shuf" => uu_shuf::uumain,
        "sleep" => uu_sleep::uumain,
        "sort" => uu_sort::uumain,
        "split" => uu_split::uumain,
        "tac" => uu_tac::uumain,
        "tail" => uu_tail::uumain,
        "tee" => uu_tee::uumain,
        "test" => uu_test::uumain,
        "touch" => uu_touch::uumain,
        "tr" => uu_tr::uumain,
        "true" => uu_true::uumain,
        "truncate" => uu_truncate::uumain,
        "uname" => uu_uname::uumain,
        "unexpand" => uu_unexpand::uumain,
        "uniq" => uu_uniq::uumain,
        "unlink" => uu_unlink::uumain,
        "wc" => uu_wc::uumain,
        "whoami" => uu_whoami::uumain,
        "yes" => uu_yes::uumain,
        "[" => uu_test::uumain,
        _ => return None,
    })
}

/// Runs `name` with `args` (where `args[0]` is the command name) and returns its exit code,
/// or `None` when `name` is not a coreutils command.
pub fn run(name: &str, args: Vec<OsString>) -> Option<i32> {
    let main = entry(name)?;
    uucore::set_utility_is_second_arg();
    let canonical = if name == "[" { "test" } else { name };
    if let Err(error) = uucore::locale::setup_localization(canonical) {
        eprintln!("{name}: could not load messages: {error}");
        return Some(99);
    }
    Some(main(args.into_iter()))
}
