#!/usr/bin/env python3
"""Records real Nebula output for the browser preview (src/preview-session.ts).

Runs a few commands with target/debug/nebula-sh inside a pseudo-terminal, in a small
demo project, and saves what they print. Linux or macOS only (uses `pty`).

    cargo build -p nebula-sh && python3 scripts/record-preview.py
"""
import json
import os
import pathlib
import pty
import select
import shutil
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
SHELL = ROOT / "target" / "debug" / "nebula-sh"
OUTPUT = ROOT / "src" / "preview-session.ts"
COMMANDS = ["ls", "git status --short", "grep -rn TODO src", "tree src"]

FILES = {
    "README.md": "# app\n",
    "package.json": "{}\n",
    "Cargo.toml": "[package]\nname = \"app\"\n",
    "LICENSE": "MIT\n",
    "src/main.rs": "fn main() {\n    // TODO: parse arguments\n    app::run();\n}\n",
    "src/lib.rs": "pub fn run() {}\n",
    "src/ui/theme.ts": "export const theme = {};\n",
    "src/ui/window.tsx": "// TODO: remember window size\nexport {};\n",
    "assets/logo.png": "",
    "docs/guide.md": "Guide\n",
}


def capture(command: str, cwd: pathlib.Path, home: pathlib.Path) -> str:
    pid, fd = pty.fork()
    if pid == 0:
        os.chdir(cwd)
        os.environ.update({"TERM": "xterm-256color", "NEBULA_TERMINAL": "1", "HOME": str(home), "COLUMNS": "96"})
        os.execv(str(SHELL), [str(SHELL), "-c", command])
    import fcntl
    import struct
    import termios

    fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", 30, 96, 0, 0))
    chunks = []
    while True:
        ready, _, _ = select.select([fd], [], [], 5)
        if not ready:
            break
        try:
            data = os.read(fd, 65536)
        except OSError:
            break
        if not data:
            break
        chunks.append(data)
    os.waitpid(pid, 0)
    return b"".join(chunks).decode("utf-8").replace("\r\n", "\n")


def main() -> None:
    if not SHELL.exists():
        raise SystemExit("build nebula-sh first: cargo build -p nebula-sh")
    home = pathlib.Path(tempfile.mkdtemp())
    project = home / "projects" / "app"
    for name, text in FILES.items():
        path = project / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    git = ["git", "-c", "user.name=demo", "-c", "user.email=demo@example.com"]
    subprocess.run([*git, "init", "-q", "-b", "main"], cwd=project, check=True)
    subprocess.run([*git, "add", "."], cwd=project, check=True)
    subprocess.run([*git, "commit", "-q", "-m", "init"], cwd=project, check=True)
    (project / "src" / "lib.rs").write_text("pub fn run() {\n    println!(\"hi\");\n}\n")
    (project / "notes.txt").write_text("todo\n")

    session = [{"command": command, "output": capture(command, project, home)} for command in COMMANDS]
    shutil.rmtree(home)
    OUTPUT.write_text(
        "// Generated by scripts/record-preview.py: real output of Nebula commands,\n"
        "// replayed in the browser preview where no shell can run.\n"
        f"export const previewSession: Array<{{ command: string; output: string }}> = {json.dumps(session, indent=2, ensure_ascii=False)};\n"
    )
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
