// Generated by scripts/record-preview.py: real output of Nebula commands,
// replayed in the browser preview where no shell can run.
export const previewSession: Array<{ command: string; output: string }> = [
  {
    "command": "ls",
    "output": "\u001b[01;34m  assets\u001b[0m      \u001b[01;34m  docs\u001b[0m       notes.txt       README.md\n  Cargo.toml    LICENSE    package.json  \u001b[01;34m  src\u001b[0m\n"
  },
  {
    "command": "git status --short",
    "output": " \u001b[31mM\u001b[m src/lib.rs\n\u001b[31m??\u001b[m notes.txt\n"
  },
  {
    "command": "grep -rn TODO src",
    "output": "\u001b[35msrc/main.rs\u001b[m\u001b[36m:\u001b[m\u001b[32m2\u001b[m\u001b[36m:\u001b[m    // \u001b[01;31mTODO\u001b[m: parse arguments\n\u001b[35msrc/ui/window.tsx\u001b[m\u001b[36m:\u001b[m\u001b[32m1\u001b[m\u001b[36m:\u001b[m// \u001b[01;31mTODO\u001b[m: remember window size\n"
  },
  {
    "command": "tree src",
    "output": "\u001b[01;34msrc\u001b[0m\n\u001b[02m├── \u001b[0m  lib.rs\n\u001b[02m├── \u001b[0m  main.rs\n\u001b[02m└── \u001b[0m\u001b[01;34m  ui\u001b[0m\n\u001b[02m    ├── \u001b[0m  theme.ts\n\u001b[02m    └── \u001b[0m  window.tsx\n\n1 directory, 4 files\n"
  }
];
